name: C/C++ Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y build-essential
    - name: Configure
      run: ./configure
    - name: Build
      run: make
    - name: Run tests
      run: make test
    - name: Generate documentation
      run: make docs
    - name: Create release
      run: make release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release/

